pipeline {

    agent any

    environment {

        AWS_REGION = "ap-south-1"
        CLUSTER_NAME = "banking-eks"

    }

    stages {

        stage('Checkout') {

            steps {
                checkout scm
            }

        }

        stage('Terraform Format') {

            steps {

                sh '''
                terraform fmt -recursive
                '''

            }

        }

        stage('Terraform Init') {

            steps {

                sh '''
                terraform init
                '''

            }

        }

        stage('Terraform Validate') {

            steps {

                sh '''
                terraform validate
                '''

            }

        }

        stage('Terraform Plan') {

            steps {

                sh '''
                terraform plan -out=tfplan
                '''

            }

        }

        stage('Approval') {

            steps {

                input message: "Approve Terraform Apply?"

            }

        }

        stage('Terraform Apply') {

            steps {

                sh '''
                terraform apply -auto-approve tfplan
                '''

            }

        }

        stage('Update kubeconfig') {

            steps {

                sh '''
                aws eks update-kubeconfig \
                  --region ${AWS_REGION} \
                  --name ${CLUSTER_NAME}
                '''

            }

        }

        stage('Verify Cluster') {

            steps {

                sh '''
                kubectl get nodes

                kubectl get namespaces
                '''

            }

        }

    }

    post {

        success {

            echo "Infrastructure Created Successfully"

        }

        failure {

            echo "Infrastructure Creation Failed"

        }

    }

}